paths:
  dataset_dir: "data/"
  output_dir: "data/output/"
  atlas_path: "data/atlas/AAL3v1.nii.gz"
  subject: 'all'                                                                 # if 'all' (aka None): scripts are run on the whole dataset 

tractogram_config:
  stop_method: 'ACT'                                                                    # type of stopping citerion
  fa_thres: 0.1                                                                         # fractional anisotropy threshold; originally =0.7
  seed_density: 1                                                                       # the number of seeds to place along each dimension
  max_cross: 1                                                                          # the maximum no. of direction to track from each seed in crossing voxels
  sh_order: 6                                                                           # maximal spherical harmonics order
  stop_thres: 0.25                                                                      # stopping criterion threshold
  step_size: 0.5                                                                        # step size for tracking
  take_log: True                                                                        # take the logarithm of values in connectivity matrix 
  stream_min_len: 20                                                                    # minimum length of streamlines 

  cores: 4                                                                              # Cores to use for parallel tractographies (-1 to use all available)
